# Generated by Django 4.1.3 on 2022-11-26 10:48

import PeopleSite.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dduser',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dduser',
            name='first_name',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), PeopleSite.accounts.models.is_alphabetical]),
        ),
        migrations.AlterField(
            model_name='dduser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('do_not_show', 'Do not show')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='dduser',
            name='last_name',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), PeopleSite.accounts.models.is_alphabetical]),
        ),
    ]
