# Generated by Django 4.1.3 on 2022-12-06 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_dduser_age_alter_dduser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dduser',
            name='age',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(18)]),
        ),
    ]
