# Generated by Django 4.1.3 on 2022-12-09 11:54

import PeopleSite.accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_dduser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dduser',
            name='last_name',
            field=models.CharField(max_length=2, null=True, validators=[django.core.validators.MinLengthValidator(30), PeopleSite.accounts.validators.is_alphabetical]),
        ),
    ]
