# Generated by Django 4.1.3 on 2022-12-14 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_dduser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dduser',
            name='age',
            field=models.PositiveIntegerField(error_messages='You must have 18 years to register.', null=True, validators=[django.core.validators.MinValueValidator(18)]),
        ),
    ]
