# Generated by Django 4.1.3 on 2022-12-14 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_dduser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dduser',
            name='age',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(18)]),
        ),
    ]
