# Generated by Django 4.1.3 on 2022-12-15 18:10

import PeopleSite.accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_dduser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dduser',
            name='age',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(18, message='You must have at least 18 years to register in this site!')]),
        ),
        migrations.AlterField(
            model_name='dduser',
            name='first_name',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2, message='The required name must have at least 2 letters.'), PeopleSite.accounts.validators.is_alphabetical]),
        ),
        migrations.AlterField(
            model_name='dduser',
            name='height',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='You cannot put negative value for height!')]),
        ),
        migrations.AlterField(
            model_name='dduser',
            name='last_name',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2, message='The required name must have at least 2 letters.'), PeopleSite.accounts.validators.is_alphabetical]),
        ),
        migrations.AlterField(
            model_name='dduser',
            name='weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='You cannot put negative value for weight!')]),
        ),
    ]
