# Generated by Django 4.1.3 on 2022-12-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_photolike_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photolike',
            old_name='user',
            new_name='person',
        ),
    ]
