# Generated by Django 4.1.3 on 2022-12-03 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0002_alter_photo_description'),
        ('common', '0003_photolike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photolike',
            name='photo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='photos.photo'),
        ),
        migrations.AlterField(
            model_name='photolike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
